// Code generated by tools/build.py from sheets/weapons.json and sheets/cs2_settings.json. DO NOT EDIT.

package main

var sheetWeapons = []weaponRow{
	{ID: "CSNVPistol", Name: "P-18 Sidearm", BaseForm: 0x0E3778, PluginForm: 0x000800, DamageMult: 1, ClipSize: 20, FireRateMult: 1.2, Automatic: false},
	{ID: "CSNVRifle", Name: "K-47 Rifle", BaseForm: 0x0E9C3B, PluginForm: 0x000801, DamageMult: 1.15, ClipSize: 30, FireRateMult: 1, Automatic: true},
	{ID: "CSNVSniper", Name: "Magnum Longshot", BaseForm: 0x004353, PluginForm: 0x000802, DamageMult: 1.6, ClipSize: 5, FireRateMult: 0.8, Automatic: false},
}

var sheetCS2Defaults = map[string]string{
	"buymenu":               "b",
	"cl_crosshaircolor":     "1",
	"cl_crosshaircolor_r":   "50",
	"cl_crosshaircolor_g":   "250",
	"cl_crosshaircolor_b":   "50",
	"cl_crosshairalpha":     "200",
	"cl_crosshairsize":      "5",
	"cl_crosshairgap":       "1",
	"cl_crosshairthickness": "0.5",
	"cl_crosshairdot":       "0",
}
