#!/usr/bin/env python3
"""Generate code from the sheets (one struct per row), then optionally package the release.
  python3 tools/build.py            -> mod/data.lua, bridge/SheetData.g.cs
  python3 tools/build.py --release  -> also publishes the bridge and writes build/CrabRun-<ver>.zip
"""
import json, os, sys, subprocess, zipfile, hashlib, shutil
HERE = os.path.dirname(os.path.abspath(__file__)); ROOT = os.path.dirname(HERE)
sys.path.insert(0, HERE)
from preflight import load, preflight

VERSION = open(os.path.join(ROOT, "VERSION")).read().strip()

def lua(v, ind=""):
    if isinstance(v, bool): return "true" if v else "false"
    if isinstance(v, (int, float)): return repr(v)
    if isinstance(v, str): return json.dumps(v)  # JSON string escapes are valid Lua escapes for ASCII
    if isinstance(v, list): return "{" + ", ".join(lua(x, ind) for x in v) + "}"
    if isinstance(v, dict):
        inner = ind + "  "
        return "{\n" + "".join(f"{inner}{k} = {lua(x, inner)},\n" for k, x in v.items()) + ind + "}"
    raise TypeError(v)

DROP = {"verified", "in_game", "source"}  # bookkeeping columns, not runtime data

def gen_lua(s):
    out = ["-- GENERATED by tools/build.py from sheets/*.json. Edit the sheets, not this file.",
           f"return {{\n  version = {json.dumps(VERSION)},"]
    for name in sorted(s):
        rows = [{k: v for k, v in r.items() if k not in DROP} for r in s[name]]
        if name == "systems":
            out.append(f"  systems = {lua(rows[0], '  ')},")
        else:
            out.append(f"  {name} = {{")
            for r in rows: out.append("    " + lua(r, "    ") + ",")
            out.append("  },")
    out.append("}")
    return "\n".join(out) + "\n"

def cs_str(x): return json.dumps(x)

def gen_cs(s):
    L = ["// GENERATED by tools/build.py from sheets/*.json. Edit the sheets, not this file.",
         "namespace CrabRun;", "public static class SheetData {",
         f"  public const string Version = {cs_str(VERSION)};",
         "  public record SoundRow(string Event, string[] Keywords, string[] FallbackKeywords, float Volume, bool Loop);",
         "  public record ArtRow(string Id, string[] Keywords, string[] FallbackKeywords);",
         "  public record PerkRow(string Key, string FallbackName);",
         "  public record KeyRow(string Key, int Vk, string Action);"]
    arr = lambda xs: "new[]{" + ",".join(cs_str(x) for x in xs) + "}"
    L.append("  public static readonly SoundRow[] Sounds = {")
    for r in s["crab_sounds"]:
        L.append(f"    new({cs_str(r['event'])}, {arr(r['keywords'])}, {arr(r['fallback_keywords'])}, {r['volume']}f, {str(r['loop']).lower()}),")
    L.append("  };"); L.append("  public static readonly ArtRow[] Art = {")
    for r in s["crab_art"]:
        L.append(f"    new({cs_str(r['id'])}, {arr(r['keywords'])}, {arr(r['fallback_keywords'])}),")
    L.append("  };"); L.append("  public static readonly PerkRow[] Perks = {")
    for r in s["crab_perks"]:
        L.append(f"    new({cs_str(r['key'])}, {cs_str(r['fallback_name'])}),")
    L.append("  };"); L.append("  public static readonly KeyRow[] Keys = {")
    for r in s["keys"]:
        L.append(f"    new({cs_str(r['key'])}, {r['vk']}, {cs_str(r['action'])}),")
    L.append("  };"); L.append("}")
    return "\n".join(L) + "\n"

def write(path, text):
    p = os.path.join(ROOT, path)
    if not os.path.exists(p) or open(p).read() != text:
        open(p, "w", newline="\n").write(text); print("wrote", path)

MOD_FILES = ["init.lua", "data.lua", "util.lua", "rng.lua", "game.lua", "run.lua", "shop.lua", "perks.lua", "hud.lua", "bridge.lua"]

def release():
    pub = os.path.join(ROOT, "build", "bridge")
    shutil.rmtree(pub, ignore_errors=True)
    dotnet = shutil.which("dotnet") or os.path.expanduser("~/.dotnet/dotnet")
    subprocess.check_call([dotnet, "publish", os.path.join(ROOT, "bridge", "CrabRunBridge.csproj"), "-c", "Release",
                           "-r", "win-x64", "--self-contained", "true", "-p:PublishSingleFile=true",
                           "-p:IncludeNativeLibrariesForSelfExtract=true", "-p:DebugType=none", "-o", pub])
    exe = os.path.join(pub, "CrabRunBridge.exe")
    extra = [f for f in os.listdir(pub) if f != "CrabRunBridge.exe"]
    if extra: raise SystemExit(f"publish left loose files next to the exe: {extra}")
    zpath = os.path.join(ROOT, "build", f"CrabRun-{VERSION}.zip")
    modroot = "bin/x64/plugins/cyber_engine_tweaks/mods/CrabRun/"
    with zipfile.ZipFile(zpath, "w", zipfile.ZIP_DEFLATED) as z:
        for f in MOD_FILES:
            z.write(os.path.join(ROOT, "mod", f), modroot + f)
        z.writestr(modroot + "io/README.txt", "Crab Run writes its bridge channel files here (events.txt, keys.txt).\n")
        z.write(exe, "CrabRun/CrabRunBridge.exe")
        for f in ("README.md", "CREDITS.md", "LICENSE", "THIRD-PARTY-NOTICES.md"):
            z.write(os.path.join(ROOT, f), "CrabRun/" + f)
    data = open(zpath, "rb").read()
    print(f"{zpath}: {len(data)} bytes sha256 {hashlib.sha256(data).hexdigest()}")

if __name__ == "__main__":
    s = load()
    errors, _, _ = preflight(s)
    if errors:
        print("preflight failed; run tools/preflight.py"); sys.exit(1)
    write("mod/data.lua", gen_lua(s))
    write("bridge/SheetData.g.cs", gen_cs(s))
    if "--release" in sys.argv: release()
