#!/usr/bin/env python3
"""Builds CS2 in the Mojave from the design sheets.

Every generated file comes from sheets/*.json; edit a sheet, then rebuild. Steps:
  1. preflight (refuses to build on unfilled cells or broken references)
  2. New Vegas side -> build/stage/Data/...: the xNVSE main script, the JIP runner line,
     the HUD and buy-screen XML, textures, default csnv_cs2.ini
  3. launcher/sheets_gen.go (the launcher's copy of the weapons and cs2_settings sheets)
  4. csnv-launch.exe (Go, cross-compiled for Windows) -> build/stage/CSNV/
  5. build/CSNV-<version>.zip

Usage: python3 tools/build.py [--version 0.1.0] [--no-exe] [--release]
"""
import argparse
import json
import shutil
import subprocess
import sys
import zipfile
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from img import read_png, write_dds  # noqa: E402

ROOT = Path(__file__).resolve().parent.parent
SHEETS = ROOT / "sheets"
STAGE = ROOT / "build" / "stage"
DATA = STAGE / "Data"
JIP_DLL = ROOT / "vendor" / "jip_nvse.dll"
INI = "csnv_cs2.ini"


def load_sheets():
    out = {}
    for path in sorted(SHEETS.glob("*.json")):
        data = json.loads(path.read_text())
        out[data["sheet"]] = data["rows"]
    return out


def by_id(rows):
    return {r["id"]: r for r in rows}


def rgb(text):
    return [int(v) for v in text.split(",")]


# ---------------------------------------------------------------- scripts

def setting_default(cs2, sid):
    return float(cs2[sid]["default"])


def main_script(s):
    weapons, buys, cs2 = by_id(s["weapons"]), sorted(s["buy_menu"], key=lambda r: r["slot"]), by_id(s["cs2_settings"])
    hud, hide = by_id(s["hud"]), s["hud_hide"]
    L = []
    a = L.append
    a("begin Function { }")
    a("; CS2 in the Mojave - main script, run on every load and new game by Data/NVSE/Plugins/scripts/ln_csnv.txt.")
    a("; Generated by tools/build.py from sheets/*.json. Edit the sheets, not this file.")
    a("")
    a("\tint iKey = 48")
    a("\tint iBad = 0")
    a("\tfloat fVal = 0")
    a("\tfloat fLen = %g" % (setting_default(cs2, "xhair_size") * 2))
    a("\tfloat fGap = %g" % (4 + setting_default(cs2, "xhair_gap")))
    a("\tfloat fThick = %g" % max(1, round(setting_default(cs2, "xhair_thickness") * 2)))
    a("\tfloat fDot = %g" % (2 if setting_default(cs2, "xhair_dot") else 1))
    a("\tref rForm")
    a("\tref rOnKey")
    a("\tref rOnMenu")
    a("\tref rHudTick")
    a("\tref rAlways")
    a("")
    a("\t; hook load_settings: values the launcher wrote from the player's CS2 files (0 = missing -> keep default)")
    a('\tlet fVal := GetINIFloat "Keys:BuyKey" "%s"' % INI)
    a("\tif fVal > 0")
    a("\t\tlet iKey := fVal")
    a("\tendif")
    for var, key in (("fLen", "Length"), ("fGap", "Gap"), ("fThick", "Thickness")):
        a('\tlet fVal := GetINIFloat "Crosshair:%s" "%s"' % (key, INI))
        a("\tif fVal > 0")
        a("\t\tlet %s := fVal" % var)
        a("\tendif")
    a('\tif eval (GetINIFloat "Crosshair:Dot" "%s") > 0' % INI)
    a("\t\tlet fDot := 2")
    a("\tendif")
    a("")
    a("\t; hook resolve_forms: the launcher-built weapons in CSNV.esp, their ammo and caps")
    for w in weapons.values():
        for mod, fid, what in (("CSNV.esp", w["plugin_form"], "weapon %s" % w["name"]),
                               ("FalloutNV.esm", w["ammo_form"], "ammo for %s" % w["name"])):
            a('\tlet rForm := GetFormFromMod "%s" "%s"' % (mod, fid))
            a("\tif eval !(IsFormValid rForm)")
            a('\t\tPrintToConsole "CSNV error: %s %s (%s) not found"' % (mod, fid, what))
            a("\t\tlet iBad += 1")
            a("\tendif")
    a('\tlet rForm := GetFormFromMod "FalloutNV.esm" "00000F"')
    a('\tPlayerRef.AuxVarSetRef "*_CSNVCaps" rForm')
    a("")
    a("\t; once per game session: HUD layer and event handlers (they survive loading a save)")
    a('\tif eval !(PlayerRef.AuxVarGetFlt "*_CSNVSession")')
    a('\t\tPlayerRef.AuxVarSetFlt "*_CSNVSession" 1')
    a("\t\t; hook hud_overlay")
    a('\t\tInjectUIXML "HUDMainMenu" "Data\\menus\\csnv\\csnv_hud.xml"')
    a("")
    a("\t\t; hook key_buy_menu -> buy_screen_open")
    a("\t\tlet rOnKey := (begin Function {int iPressed}")
    a("\t\t\tref rBuy")
    a("\t\t\tref rCaps")
    a("\t\t\tfloat fCaps")
    a("\t\t\tif MenuMode")
    a("\t\t\t\treturn")
    a("\t\t\tendif")
    a("\t\t\tlet rBuy := (begin Function {int iButton}")
    a("\t\t\t\tref rW")
    a("\t\t\t\tref rA")
    a("\t\t\t\tref rC")
    a("\t\t\t\tint iPrice")
    a("\t\t\t\tint iAmmo")
    a('\t\t\t\tPlayerRef.AuxVarSetFlt "*_CSNVBuyOpen" 0')
    for i, b in enumerate(buys):
        w = weapons[b["weapon"]]
        a("\t\t\t\t%s iButton == %d" % ("if" if i == 0 else "elseif", i))
        a('\t\t\t\t\tlet rW := GetFormFromMod "CSNV.esp" "%s"' % w["plugin_form"])
        a('\t\t\t\t\tlet rA := GetFormFromMod "FalloutNV.esm" "%s"' % w["ammo_form"])
        a("\t\t\t\t\tlet iPrice := %d" % b["price_caps"])
        a("\t\t\t\t\tlet iAmmo := %d" % w["starter_ammo"])
    a("\t\t\t\telse")
    a("\t\t\t\t\treturn")
    a("\t\t\t\tendif")
    a("\t\t\t\tif eval !(IsFormValid rW)")
    a('\t\t\t\t\tMessageEx "CS2 in the Mojave: that weapon is missing. Start the game from Melty."')
    a("\t\t\t\t\treturn")
    a("\t\t\t\tendif")
    a('\t\t\t\tlet rC := PlayerRef.AuxVarGetRef "*_CSNVCaps"')
    a("\t\t\t\t; hook spend_caps")
    a("\t\t\t\tif eval (PlayerRef.GetItemCount rC) < iPrice")
    a('\t\t\t\t\tMessageEx "Not enough caps: that costs %g." iPrice')
    a("\t\t\t\t\treturn")
    a("\t\t\t\tendif")
    a("\t\t\t\tPlayerRef.RemoveItem rC iPrice 1")
    a("\t\t\t\t; hook give_item")
    a("\t\t\t\tPlayerRef.AddItem rW 1 1")
    a("\t\t\t\tif eval IsFormValid rA")
    a("\t\t\t\t\tPlayerRef.AddItem rA iAmmo 1")
    a("\t\t\t\tendif")
    a("\t\t\t\tPlayerRef.EquipItem rW 0 1")
    a('\t\t\t\tMessageEx "Bought %n for %g caps." rW iPrice')
    a("\t\t\tend)")
    a('\t\t\tlet rCaps := PlayerRef.AuxVarGetRef "*_CSNVCaps"')
    a("\t\t\tlet fCaps := PlayerRef.GetItemCount rCaps")
    a('\t\t\tPlayerRef.AuxVarSetFlt "*_CSNVBuyOpen" 1')
    buttons = "|".join("%s  $%d" % (weapons[b["weapon"]]["name"], b["price_caps"]) for b in buys)
    a('\t\t\tMessageBoxExAlt rBuy "^BUY MENU^You have %%.0f caps.|%s|Cancel" fCaps' % buttons)
    a("\t\tend)")
    a("\t\tSetOnKeyDownEventHandler rOnKey 1 iKey")
    a("")
    a("\t\t; hook buy_screen_style: CS2 layer on the game's message menu (1001), only for our buy screen")
    a("\t\tlet rOnMenu := (begin Function {int iMenu}")
    a("\t\t\tref rCaps")
    a('\t\t\tif eval (PlayerRef.AuxVarGetFlt "*_CSNVBuyOpen") == 0')
    a("\t\t\t\treturn")
    a("\t\t\tendif")
    a('\t\t\tInjectUIXML "MessageMenu" "Data\\menus\\csnv\\csnv_buy.xml"')
    a('\t\t\tlet rCaps := PlayerRef.AuxVarGetRef "*_CSNVCaps"')
    a("\t\t\tlet fCaps := PlayerRef.GetItemCount rCaps")
    a('\t\t\tSetUIStringEx "MessageMenu/CSNV_Buy/bs_caps/string" "$ %.0f" fCaps')
    a("\t\tend)")
    a("\t\tSetOnMenuOpenEventHandler rOnMenu 1 1001")
    a("\tendif")
    a("")
    a("\t; crosshair geometry from the player's CS2 settings (the colour is in xhair.dds, written by the launcher)")
    a('\tSetUIFloat "HUDMainMenu/CSNV_HUD/user0" fLen')
    a('\tSetUIFloat "HUDMainMenu/CSNV_HUD/user1" fGap')
    a('\tSetUIFloat "HUDMainMenu/CSNV_HUD/user2" fThick')
    a('\tSetUIFloat "HUDMainMenu/CSNV_HUD/user3" fDot')
    a("")
    a("\t; hook hud_update + hide_vanilla_hud: delayed calls are cleared on load, so this restarts every load")
    a("\tlet rHudTick := (begin Function { }")
    a("\t\tref rAm")
    a("\t\tref rC")
    a("\t\tfloat fClip")
    a("\t\tfloat fRes")
    a("\t\tfloat fNum")
    a("\t\tlet fNum := PlayerRef.GetAV Health")
    a('\t\tSetUIStringEx "HUDMainMenu/CSNV_HUD/hud_health/string" "%s" fNum'
      % hud["hud_health"]["format"].replace("{value}", "%.0f"))
    a("\t\tlet fNum := PlayerRef.GetAV DamageThreshold")
    a('\t\tSetUIStringEx "HUDMainMenu/CSNV_HUD/hud_armor/string" "%s" fNum'
      % hud["hud_armor"]["format"].replace("{value}", "%.0f"))
    a('\t\tlet rC := PlayerRef.AuxVarGetRef "*_CSNVCaps"')
    a("\t\tlet fNum := PlayerRef.GetItemCount rC")
    a('\t\tSetUIStringEx "HUDMainMenu/CSNV_HUD/hud_caps/string" "%s" fNum'
      % hud["hud_caps"]["format"].replace("{value}", "%.0f"))
    a("\t\tlet rAm := GetPlayerCurrentAmmo")
    a("\t\tif eval IsFormValid rAm")
    a("\t\t\tlet fClip := GetPlayerCurrentAmmoRounds")
    a("\t\t\tlet fRes := (PlayerRef.GetItemCount rAm) - fClip")
    a("\t\t\tif fRes < 0")
    a("\t\t\t\tlet fRes := 0")
    a("\t\t\tendif")
    a('\t\t\tSetUIStringEx "HUDMainMenu/CSNV_HUD/hud_ammo/string" "%s" fClip fRes'
      % hud["hud_ammo"]["format"].replace("{clip}", "%.0f").replace("{reserve}", "%.0f"))
    a("\t\telse")
    a('\t\t\tSetUIStringEx "HUDMainMenu/CSNV_HUD/hud_ammo/string" " "')
    a("\t\tendif")
    for h in hide:
        a('\t\tSetUIFloat "HUDMainMenu/%s/visible" 0' % h["tile"])
    a("\tend)")
    a("\tlet rAlways := (begin Function { }")
    a("\t\tSetFunctionValue 1")
    a("\tend)")
    refresh = 0.1
    a("\tCallWhilePerSeconds %g rHudTick rAlways" % refresh)
    a("")
    a("\tif iBad > 0")
    a('\t\tPrintToConsole "CS2 in the Mojave: %g form(s) missing, see the CSNV error lines above." iBad')
    a("\telse")
    a('\t\tPrintToConsole "CS2 in the Mojave: ready. Buy key scancode %g." iKey')
    a("\tendif")
    a("end")
    return "\n".join(L) + "\n"


RUNNER = ('; CS2 in the Mojave: JIP LN script runner entry (ln_ = on every load and new game).\n'
          '; Runs the main script that xNVSE precompiles from Data/NVSE/user_defined_functions/csnv/.\n'
          'Call (CompileScript "csnv\\csnv_main.txt")\n')


# ---------------------------------------------------------------- UI XML

def text_tile(name, x, y, string, color, alpha=255, font=3):
    r, g, b = color
    return (f'\t<text name="{name}">\n\t\t<x>{x}</x>\n\t\t<y>{y}</y>\n\t\t<font>{font}</font>\n'
            f'\t\t<string>{string}</string>\n\t\t<red>{r}</red>\n\t\t<green>{g}</green>\n\t\t<blue>{b}</blue>\n'
            f'\t\t<alpha>{alpha}</alpha>\n\t\t<depth>5</depth>\n\t\t<visible>&true;</visible>\n\t</text>\n')


def image_tile(name, x, y, w, h, tex, extra=""):
    return (f'\t<image name="{name}">\n\t\t<filename>interface\\csnv\\{tex}</filename>\n\t\t<x>{x}</x>\n\t\t<y>{y}</y>\n'
            f'\t\t<width>{w}</width>\n\t\t<height>{h}</height>\n\t\t<depth>5</depth>\n{extra}'
            f'\t\t<visible>&true;</visible>\n\t</image>\n')


def hud_xml(s):
    hud = by_id(s["hud"])
    white = (235, 235, 235)
    sw, sh = '<copy src="screen()" trait="width"/>', '<copy src="screen()" trait="height"/>'

    def pos(row, dx=0):
        if row["anchor"] == "bottom-left":
            return row["x"] + dx, f'{sh}<sub>{row["y"]}</sub>'
        if row["anchor"] == "bottom-right":
            return f'{sw}<sub>{row["x"] + 160 - dx}</sub>', f'{sh}<sub>{row["y"]}</sub>'
        raise ValueError(row["anchor"])

    out = ['<!-- CS2 in the Mojave HUD layer, injected into HUDMainMenu. Generated from sheets/hud.json. -->\n',
           '<rect name="CSNV_HUD">\n',
           '\t<user0>10</user0> <!-- crosshair arm length (set from CS2 cl_crosshairsize) -->\n',
           '\t<user1>5</user1> <!-- crosshair gap -->\n',
           '\t<user2>1</user2> <!-- crosshair thickness -->\n',
           '\t<user3>1</user3> <!-- centre dot: 2 = shown, 1 = hidden -->\n',
           '\t<visible>&true;</visible>\n']
    for hid in ("hud_health", "hud_caps", "hud_ammo"):
        x, y = pos(hud[hid])
        out.append(text_tile(hid, x, y, hud[hid]["format"].replace("{value}", "0").replace("{clip}", "0")
                             .replace("{reserve}", "0"), white))
    arm = hud["hud_armor"]
    x, y = pos(arm)
    out.append(image_tile("hud_armor_icon", x, f"{y}<add>2</add>", 28, 28, "armor.dds"))
    x, y = pos(arm, 36)
    out.append(text_tile("hud_armor", x, y, "0", white))
    # crosshair: four arms and a dot around the screen centre, sized by the user traits above
    cx, cy = f'{sw}<div>2</div>', f'{sh}<div>2</div>'
    L, G, T = ('<{op} src="parent()" trait="user0"/>', '<{op} src="parent()" trait="user1"/>',
               '<{op} src="parent()" trait="user2"/>')
    half_t = '<sub><copy src="parent()" trait="user2"/><div>2</div></sub>'
    arms = {
        "xh_left": (cx + G.format(op="sub") + L.format(op="sub"), cy + half_t, L.format(op="copy"), T.format(op="copy")),
        "xh_right": (cx + G.format(op="add"), cy + half_t, L.format(op="copy"), T.format(op="copy")),
        "xh_top": (cx + half_t, cy + G.format(op="sub") + L.format(op="sub"), T.format(op="copy"), L.format(op="copy")),
        "xh_bottom": (cx + half_t, cy + G.format(op="add"), T.format(op="copy"), L.format(op="copy")),
    }
    for name, (x, y, w, h) in arms.items():
        out.append(image_tile(name, x, y, w, h, "xhair.dds"))
    dot = image_tile("xh_dot", cx + half_t, cy + half_t, T.format(op="copy"), T.format(op="copy"), "xhair.dds")
    out.append(dot.replace("\t\t<visible>&true;</visible>\n", '\t\t<visible><copy src="parent()" trait="user3"/></visible>\n'))
    out.append("</rect>\n")
    return "".join(out)


def buy_xml(s):
    screen = s["buy_screen"]
    weapons = by_id(s["weapons"])
    rows_by_screen = {b["screen_row"]: b for b in s["buy_menu"]}
    out = ['<!-- CS2 in the Mojave buy screen layer, injected into MessageMenu. Generated from sheets/buy_screen.json. -->\n',
           '<rect name="CSNV_Buy">\n\t<visible>&true;</visible>\n']
    for row in screen:
        if row["kind"] in ("panel", "bar"):
            out.append(image_tile(row["id"], row["x"], row["y"], row["width"], row["height"], row["id"] + ".dds"))
            continue
        text = row["text"].replace("{caps}", "0")
        if row["id"] in rows_by_screen:
            b = rows_by_screen[row["id"]]
            text = text.replace("{name}", weapons[b["weapon"]]["name"]).replace("{price}", str(b["price_caps"]))
        font = 1 if row["id"] == "bs_header" else 3
        out.append(text_tile(row["id"], row["x"], row["y"], text, rgb(row["color"]), row["alpha"], font))
    out.append("</rect>\n")
    return "".join(out)


# ---------------------------------------------------------------- textures, ini, go

def solid(rgba, size=8):
    return [[tuple(rgba)] * size for _ in range(size)]


def xhair_default_rgba(cs2):
    presets = {0: (250, 50, 50), 1: (50, 250, 50), 2: (250, 250, 50), 3: (50, 50, 250), 4: (50, 250, 250)}
    preset = int(float(cs2["xhair_color"]["default"]))
    r, g, b = presets.get(preset, (int(cs2["xhair_r"]["default"]), int(cs2["xhair_g"]["default"]), int(cs2["xhair_b"]["default"])))
    return r, g, b, 255


def write_textures(s):
    tex = DATA / "textures" / "interface" / "csnv"
    tex.mkdir(parents=True, exist_ok=True)
    w, h, px = read_png(ROOT / "assets" / "armor.png")
    write_dds(tex / "armor.dds", w, h, px)
    for row in s["buy_screen"]:
        if row["kind"] in ("panel", "bar"):
            write_dds(tex / (row["id"] + ".dds"), 8, 8, solid(rgb(row["color"]) + [row["alpha"]]))
    write_dds(tex / "xhair.dds", 8, 8, solid(xhair_default_rgba(by_id(s["cs2_settings"]))))


def default_ini(s):
    cs2 = by_id(s["cs2_settings"])
    r, g, b, _ = xhair_default_rgba(cs2)
    return ("; CS2 in the Mojave: CS2 settings. Rewritten by csnv-launch.exe before every Play;\n"
            "; these are CS2's own defaults, used until the launcher has read your CS2 files.\n"
            "[Keys]\nBuyKey=48\n[Crosshair]\n"
            f"R={r}\nG={g}\nB={b}\nAlpha=255\n"
            f"Length={float(cs2['xhair_size']['default']) * 2:g}\nGap={4 + float(cs2['xhair_gap']['default']):g}\n"
            f"Thickness={max(1, round(float(cs2['xhair_thickness']['default']) * 2))}\nDot={int(float(cs2['xhair_dot']['default']))}\n"
            "Source=defaults\n")


def go_sheets(s):
    lines = ["// Code generated by tools/build.py from sheets/weapons.json and sheets/cs2_settings.json. DO NOT EDIT.", "",
             "package main", "", "var sheetWeapons = []weaponRow{"]
    for w in s["weapons"]:
        lines.append('\t{ID: "%s", Name: "%s", BaseForm: 0x%s, PluginForm: 0x%s, DamageMult: %g, ClipSize: %d, FireRateMult: %g, Automatic: %s},'
                     % (w["id"], w["name"], w["base_form"], w["plugin_form"], w["damage_mult"], w["clip_size"],
                        w["fire_rate_mult"], "true" if w["automatic"] else "false"))
    lines += ["}", "", "var sheetCS2Defaults = map[string]string{"]
    for r in s["cs2_settings"]:
        lines.append('\t"%s": "%s",' % (r["cs2_key"], r["default"]))
    lines += ["}", ""]
    return "\n".join(lines)


# ---------------------------------------------------------------- main

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--version", default="0.1.0")
    ap.add_argument("--no-exe", action="store_true", help="skip the Go build (scripts and XML only)")
    ap.add_argument("--release", action="store_true", help="fail instead of warning when vendor/jip_nvse.dll is missing")
    args = ap.parse_args()

    if subprocess.run([sys.executable, str(ROOT / "tools" / "preflight.py")], stdout=subprocess.DEVNULL).returncode:
        sys.exit("preflight is not clean: run tools/preflight.py and fix the sheets first")
    s = load_sheets()

    shutil.rmtree(STAGE, ignore_errors=True)
    udf = DATA / "NVSE" / "user_defined_functions" / "csnv"
    runner = DATA / "NVSE" / "Plugins" / "scripts"
    menus = DATA / "menus" / "csnv"
    config = DATA / "config"
    for d in (udf, runner, menus, config):
        d.mkdir(parents=True, exist_ok=True)
    (udf / "csnv_main.txt").write_text(main_script(s), newline="\r\n")
    (runner / "ln_csnv.txt").write_text(RUNNER, newline="\r\n")
    (menus / "csnv_hud.xml").write_text(hud_xml(s), newline="\r\n")
    (menus / "csnv_buy.xml").write_text(buy_xml(s), newline="\r\n")
    (config / INI).write_text(default_ini(s), newline="\r\n")
    write_textures(s)
    (ROOT / "launcher" / "sheets_gen.go").write_text(go_sheets(s))
    subprocess.run(["gofmt", "-w", "sheets_gen.go"], cwd=ROOT / "launcher", check=True)

    managed = STAGE / "CSNV"
    managed.mkdir(parents=True, exist_ok=True)
    for name in ("README.md", "CREDITS.md", "TESTING.md", "LICENSE"):
        if (ROOT / name).exists():
            shutil.copy(ROOT / name, managed / name)
    if JIP_DLL.exists():
        plug = DATA / "NVSE" / "Plugins"
        shutil.copy(JIP_DLL, plug / "jip_nvse.dll")
        (plug / "textinput").mkdir(exist_ok=True)  # part of JIP LN's own install (its text-input menu)
        shutil.copy(ROOT / "vendor" / "textinput" / "texteditmenu.xml", plug / "textinput" / "texteditmenu.xml")
        shutil.copy(ROOT / "vendor" / "JIP-LN-NVSE-LICENSE.txt", managed / "JIP-LN-NVSE-LICENSE.txt")
    elif args.release:
        sys.exit("vendor/jip_nvse.dll is missing: a release without JIP LN NVSE does not work (see vendor/README.md)")
    else:
        print("WARNING: vendor/jip_nvse.dll is missing; the package will not work until it is added (see vendor/README.md)")

    if not args.no_exe:
        subprocess.run(["go", "build", "-trimpath", "-ldflags", "-s -w -H windowsgui", "-o", str(managed / "csnv-launch.exe"), "."],
                       cwd=ROOT / "launcher", check=True, env={**__import__("os").environ, "GOOS": "windows", "GOARCH": "amd64", "CGO_ENABLED": "0"})

    zpath = ROOT / "build" / f"CSNV-{args.version}.zip"
    with zipfile.ZipFile(zpath, "w", zipfile.ZIP_DEFLATED) as z:
        for f in sorted(STAGE.rglob("*")):
            if f.is_file():
                z.write(f, f.relative_to(STAGE).as_posix())
    print(f"built {zpath.relative_to(ROOT)} ({zpath.stat().st_size} bytes)")
    for f in sorted(STAGE.rglob("*")):
        if f.is_file():
            print("  ", f.relative_to(STAGE).as_posix())


if __name__ == "__main__":
    main()
