#!/usr/bin/env python3
"""Builds CS2 in the Mojave from the design sheets.

Every generated file comes from sheets/*.json; edit a sheet, then rebuild. Steps:
  1. preflight (refuses to build on unfilled cells or broken references)
  2. New Vegas side -> build/stage/Data/...: the xNVSE main script, the JIP runner line,
     the HUD and buy-screen XML, textures, default csnv_cs2.ini
  3. launcher/sheets_gen.go (the launcher's copy of the weapons and cs2_settings sheets)
  4. csnv-launch.exe (Go, cross-compiled for Windows) -> build/stage/CSNV/
  5. build/CSNV-<version>.zip

Usage: python3 tools/build.py [--version 0.1.0] [--no-exe] [--release]
"""
import argparse
import json
import shutil
import subprocess
import sys
import zipfile
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from img import read_png, write_dds  # noqa: E402

ROOT = Path(__file__).resolve().parent.parent
SHEETS = ROOT / "sheets"
STAGE = ROOT / "build" / "stage"
DATA = STAGE / "Data"
JIP_DLL = ROOT / "vendor" / "jip_nvse.dll"
INI = "csnv_cs2.ini"


def load_sheets():
    out = {}
    for path in sorted(SHEETS.glob("*.json")):
        data = json.loads(path.read_text())
        out[data["sheet"]] = data["rows"]
    return out


def by_id(rows):
    return {r["id"]: r for r in rows}


def rgb(text):
    return [int(v) for v in text.split(",")]


# ---------------------------------------------------------------- scripts

def setting_default(cs2, sid):
    return float(cs2[sid]["default"])


UDF_DIR = "csnv"
# xNVSE caps an expression in parentheses at 512 characters, and an inline lambda counts as one, so every
# handler is its own function file in Data/NVSE/user_defined_functions/csnv/, fetched with CompileScript.


def udf_ref(name):
    return 'CompileScript "%s\\%s.txt"' % (UDF_DIR, name)


def header(L, args, what):
    L.append("begin Function {%s}" % args)
    L.append("; CS2 in the Mojave - %s." % what)
    L.append("; Generated by tools/build.py from sheets/*.json. Edit the sheets, not this file.")


def main_script(s):
    """csnv_main: runs on every load and new game (via ln_csnv.txt)."""
    weapons, cs2 = by_id(s["weapons"]), by_id(s["cs2_settings"])
    L = []
    a = L.append
    header(L, " ", "main script, run on every load and new game by Data/NVSE/Plugins/scripts/ln_csnv.txt")
    a("\tint iKey = 48")
    a("\tint iBad = 0")
    a("\tfloat fVal = 0")
    a("\tfloat fLen = %g" % (setting_default(cs2, "xhair_size") * 2))
    a("\tfloat fGap = %g" % (4 + setting_default(cs2, "xhair_gap")))
    a("\tfloat fThick = %g" % max(1, round(setting_default(cs2, "xhair_thickness") * 2)))
    a("\tfloat fDot = %g" % (2 if setting_default(cs2, "xhair_dot") else 1))
    a("\tref rForm")
    a("\tref rFn")
    a("\tref rCond")
    a("")
    a("\t; hook load_settings: values the launcher wrote from the player's CS2 files (0 = missing -> keep default)")
    a('\tlet fVal := GetINIFloat "Keys:BuyKey" "%s"' % INI)
    a("\tif fVal > 0")
    a("\t\tlet iKey := fVal")
    a("\tendif")
    for var, key in (("fLen", "Length"), ("fGap", "Gap"), ("fThick", "Thickness")):
        a('\tlet fVal := GetINIFloat "Crosshair:%s" "%s"' % (key, INI))
        a("\tif fVal > 0")
        a("\t\tlet %s := fVal" % var)
        a("\tendif")
    a('\tlet fVal := GetINIFloat "Crosshair:Dot" "%s"' % INI)
    a("\tif fVal > 0")
    a("\t\tlet fDot := 2")
    a("\tendif")
    a("")
    a("\t; hook resolve_forms: the launcher-built weapons in CSNV.esp, their ammo and caps")
    for w in weapons.values():
        for mod, fid, what in (("CSNV.esp", w["plugin_form"], "weapon %s" % w["name"]),
                               ("FalloutNV.esm", w["ammo_form"], "ammo for %s" % w["name"])):
            a('\tlet rForm := GetFormFromMod "%s" "%s"' % (mod, fid))
            a("\tif eval !(IsFormValid rForm)")
            a('\t\tPrintToConsole "CSNV error: %s %s (%s) not found"' % (mod, fid, what))
            a("\t\tlet iBad += 1")
            a("\tendif")
    a('\tlet rForm := GetFormFromMod "FalloutNV.esm" "00000F"')
    a('\tPlayerRef.AuxVarSetRef "*_CSNVCaps" rForm')
    a("")
    a("\t; once per game session: HUD layer and event handlers (they survive loading a save)")
    a('\tif eval !(PlayerRef.AuxVarGetFlt "*_CSNVSession")')
    a('\t\tPlayerRef.AuxVarSetFlt "*_CSNVSession" 1')
    a("\t\t; hook hud_overlay")
    a('\t\tInjectUIXML "HUDMainMenu" "Data\\menus\\csnv\\csnv_hud.xml"')
    a("\t\t; hook key_buy_menu (opens buy_screen_open)")
    a("\t\tlet rFn := %s" % udf_ref("csnv_onkey"))
    a("\t\tif eval IsFormValid rFn")
    a("\t\t\tSetOnKeyDownEventHandler rFn 1 iKey")
    a("\t\telse")
    a('\t\t\tPrintToConsole "CSNV error: csnv_onkey.txt did not compile"')
    a("\t\t\tlet iBad += 1")
    a("\t\tendif")
    a("\t\t; hook buy_screen_style: the game's message menu is 1001")
    a("\t\tlet rFn := %s" % udf_ref("csnv_onmenu"))
    a("\t\tif eval IsFormValid rFn")
    a("\t\t\tSetOnMenuOpenEventHandler rFn 1 1001")
    a("\t\telse")
    a('\t\t\tPrintToConsole "CSNV error: csnv_onmenu.txt did not compile"')
    a("\t\t\tlet iBad += 1")
    a("\t\tendif")
    a("\tendif")
    a("")
    a("\t; crosshair geometry from the player's CS2 settings (the colour is in xhair.dds, written by the launcher)")
    a('\tSetUIFloat "HUDMainMenu/CSNV_HUD/user0" fLen')
    a('\tSetUIFloat "HUDMainMenu/CSNV_HUD/user1" fGap')
    a('\tSetUIFloat "HUDMainMenu/CSNV_HUD/user2" fThick')
    a('\tSetUIFloat "HUDMainMenu/CSNV_HUD/user3" fDot')
    a("")
    a("\t; hook hud_update + hide_vanilla_hud: delayed calls are cleared on load, so this restarts every load")
    a("\tlet rFn := %s" % udf_ref("csnv_hudtick"))
    a("\tlet rCond := %s" % udf_ref("csnv_always"))
    a("\tif eval (IsFormValid rFn) && (IsFormValid rCond)")
    a("\t\tCallWhilePerSeconds 0.1 rFn rCond")
    a("\telse")
    a('\t\tPrintToConsole "CSNV error: the HUD scripts did not compile"')
    a("\t\tlet iBad += 1")
    a("\tendif")
    a("")
    a("\tif iBad > 0")
    a('\t\tPrintToConsole "CS2 in the Mojave: %g problem(s), see the CSNV error lines above." iBad')
    a("\telse")
    a('\t\tPrintToConsole "CS2 in the Mojave: ready. Buy key scancode %g." iKey')
    a("\tendif")
    a("end")
    return "\n".join(L) + "\n"


def onkey_script(s):
    """csnv_onkey: the player's CS2 buy key -> the buy screen (hooks key_buy_menu, buy_screen_open)."""
    weapons, buys = by_id(s["weapons"]), sorted(s["buy_menu"], key=lambda r: r["slot"])
    L = []
    a = L.append
    header(L, "int iPressed", "buy key handler (JIP SetOnKeyDownEventHandler)")
    a("\tref rBuy")
    a("\tref rCaps")
    a("\tfloat fCaps")
    a("\tif MenuMode")
    a("\t\treturn")
    a("\tendif")
    a("\tlet rBuy := %s" % udf_ref("csnv_buy"))
    a('\tlet rCaps := PlayerRef.AuxVarGetRef "*_CSNVCaps"')
    a("\tlet fCaps := PlayerRef.GetItemCount rCaps")
    a('\tPlayerRef.AuxVarSetFlt "*_CSNVBuyOpen" 1')
    buttons = "|".join("%s  $%d" % (weapons[b["weapon"]]["name"], b["price_caps"]) for b in buys)
    a('\tMessageBoxExAlt rBuy "^BUY MENU^You have %%.0f caps.|%s|Cancel" fCaps' % buttons)
    a("end")
    return "\n".join(L) + "\n"


def buy_script(s):
    """csnv_buy: the clicked button -> pay and give (hooks spend_caps, give_item)."""
    weapons, buys = by_id(s["weapons"]), sorted(s["buy_menu"], key=lambda r: r["slot"])
    L = []
    a = L.append
    header(L, "int iButton", "buy screen button handler (JIP MessageBoxExAlt callback, 0-based button)")
    a("\tref rW")
    a("\tref rA")
    a("\tref rC")
    a("\tint iPrice")
    a("\tint iAmmo")
    a("\tfloat fHave")
    a('\tPlayerRef.AuxVarSetFlt "*_CSNVBuyOpen" 0')
    for i, b in enumerate(buys):
        w = weapons[b["weapon"]]
        a("\t%s iButton == %d" % ("if" if i == 0 else "elseif", i))
        a('\t\tlet rW := GetFormFromMod "CSNV.esp" "%s"' % w["plugin_form"])
        a('\t\tlet rA := GetFormFromMod "FalloutNV.esm" "%s"' % w["ammo_form"])
        a("\t\tlet iPrice := %d" % b["price_caps"])
        a("\t\tlet iAmmo := %d" % w["starter_ammo"])
    a("\telse")
    a("\t\treturn")
    a("\tendif")
    a("\tif eval !(IsFormValid rW)")
    a('\t\tMessageEx "CS2 in the Mojave: that weapon is missing. Start the game from Melty."')
    a("\t\treturn")
    a("\tendif")
    a('\tlet rC := PlayerRef.AuxVarGetRef "*_CSNVCaps"')
    a("\t; hook spend_caps")
    a("\tlet fHave := PlayerRef.GetItemCount rC")
    a("\tif fHave < iPrice")
    a('\t\tMessageEx "Not enough caps: that costs %g." iPrice')
    a("\t\treturn")
    a("\tendif")
    a("\tPlayerRef.RemoveItem rC iPrice 1")
    a("\t; hook give_item")
    a("\tPlayerRef.AddItem rW 1 1")
    a("\tif eval IsFormValid rA")
    a("\t\tPlayerRef.AddItem rA iAmmo 1")
    a("\tendif")
    a("\tPlayerRef.EquipItem rW 0 1")
    a('\tMessageEx "Bought %n for %g caps." rW iPrice')
    a("end")
    return "\n".join(L) + "\n"


def onmenu_script(s):
    """csnv_onmenu: CS2 layer on the message menu, only while our buy screen opens (hook buy_screen_style)."""
    L = []
    a = L.append
    header(L, "int iMenu", "message menu open handler (JIP SetOnMenuOpenEventHandler)")
    a("\tref rCaps")
    a("\tfloat fCaps")
    a('\tlet fCaps := PlayerRef.AuxVarGetFlt "*_CSNVBuyOpen"')
    a("\tif fCaps == 0")
    a("\t\treturn")
    a("\tendif")
    a('\tInjectUIXML "MessageMenu" "Data\\menus\\csnv\\csnv_buy.xml"')
    a('\tlet rCaps := PlayerRef.AuxVarGetRef "*_CSNVCaps"')
    a("\tlet fCaps := PlayerRef.GetItemCount rCaps")
    a('\tSetUIStringEx "MessageMenu/CSNV_Buy/bs_caps/string" "$ %.0f" fCaps')
    a("end")
    return "\n".join(L) + "\n"


def hudtick_script(s):
    """csnv_hudtick: every 0.1 s, the HUD values (hooks hud_update, hide_vanilla_hud)."""
    hud, hide = by_id(s["hud"]), s["hud_hide"]
    L = []
    a = L.append
    header(L, " ", "HUD update, every 0.1 s (xNVSE CallWhilePerSeconds)")
    a("\tref rAm")
    a("\tref rC")
    a("\tfloat fClip")
    a("\tfloat fRes")
    a("\tfloat fNum")
    a("\tlet fNum := PlayerRef.GetAV Health")
    a('\tSetUIStringEx "HUDMainMenu/CSNV_HUD/hud_health/string" "%s" fNum'
      % hud["hud_health"]["format"].replace("{value}", "%.0f"))
    a("\tlet fNum := PlayerRef.GetAV DamageThreshold")
    a('\tSetUIStringEx "HUDMainMenu/CSNV_HUD/hud_armor/string" "%s" fNum'
      % hud["hud_armor"]["format"].replace("{value}", "%.0f"))
    a('\tlet rC := PlayerRef.AuxVarGetRef "*_CSNVCaps"')
    a("\tlet fNum := PlayerRef.GetItemCount rC")
    a('\tSetUIStringEx "HUDMainMenu/CSNV_HUD/hud_caps/string" "%s" fNum'
      % hud["hud_caps"]["format"].replace("{value}", "%.0f"))
    a("\tlet rAm := GetPlayerCurrentAmmo")
    a("\tif eval IsFormValid rAm")
    a("\t\tlet fClip := GetPlayerCurrentAmmoRounds")
    a("\t\tlet fRes := PlayerRef.GetItemCount rAm")
    a("\t\tlet fRes -= fClip")
    a("\t\tif fRes < 0")
    a("\t\t\tlet fRes := 0")
    a("\t\tendif")
    a('\t\tSetUIStringEx "HUDMainMenu/CSNV_HUD/hud_ammo/string" "%s" fClip fRes'
      % hud["hud_ammo"]["format"].replace("{clip}", "%.0f").replace("{reserve}", "%.0f"))
    a("\telse")
    a('\t\tSetUIStringEx "HUDMainMenu/CSNV_HUD/hud_ammo/string" " "')
    a("\tendif")
    for h in hide:
        a('\tSetUIFloat "HUDMainMenu/%s/visible" 0' % h["tile"])
    a("end")
    return "\n".join(L) + "\n"


def always_script(s):
    L = []
    header(L, " ", "condition for the HUD loop: always true")
    L += ["\tSetFunctionValue 1", "end"]
    return "\n".join(L) + "\n"


SCRIPTS = {"csnv_main": main_script, "csnv_onkey": onkey_script, "csnv_buy": buy_script,
           "csnv_onmenu": onmenu_script, "csnv_hudtick": hudtick_script, "csnv_always": always_script}


def check_script_limits(name, text):
    """Fail the build on what xNVSE rejects: >512 characters inside one pair of parentheses."""
    depth, start = 0, 0
    for i, ch in enumerate(text):
        if ch == "(":
            if depth == 0:
                start = i
            depth += 1
        elif ch == ")" and depth:
            depth -= 1
            if depth == 0 and i - start - 1 > 512:
                line = text.count("\n", 0, start) + 1
                sys.exit(f"{name}.txt line {line}: {i - start - 1} characters inside parentheses (xNVSE allows 512)")
    if "begin Function" in text and text.count("begin Function") > 1:
        sys.exit(f"{name}.txt: inline lambdas are not allowed; give the handler its own file")


RUNNER = ('; CS2 in the Mojave: JIP LN script runner entry (ln_ = on every load and new game).\n'
          '; Runs the main script that xNVSE precompiles from Data/NVSE/user_defined_functions/csnv/.\n'
          'Call (CompileScript "csnv\\csnv_main.txt")\n')


# ---------------------------------------------------------------- UI XML

def text_tile(name, x, y, string, color, alpha=255, font=3):
    r, g, b = color
    return (f'\t<text name="{name}">\n\t\t<x>{x}</x>\n\t\t<y>{y}</y>\n\t\t<font>{font}</font>\n'
            f'\t\t<string>{string}</string>\n\t\t<red>{r}</red>\n\t\t<green>{g}</green>\n\t\t<blue>{b}</blue>\n'
            f'\t\t<alpha>{alpha}</alpha>\n\t\t<depth>5</depth>\n\t\t<visible>&true;</visible>\n\t</text>\n')


def image_tile(name, x, y, w, h, tex, extra=""):
    return (f'\t<image name="{name}">\n\t\t<filename>interface\\csnv\\{tex}</filename>\n\t\t<x>{x}</x>\n\t\t<y>{y}</y>\n'
            f'\t\t<width>{w}</width>\n\t\t<height>{h}</height>\n\t\t<depth>5</depth>\n{extra}'
            f'\t\t<visible>&true;</visible>\n\t</image>\n')


def hud_xml(s):
    hud = by_id(s["hud"])
    white = (235, 235, 235)
    sw, sh = '<copy src="screen()" trait="width"/>', '<copy src="screen()" trait="height"/>'

    def pos(row, dx=0):
        if row["anchor"] == "bottom-left":
            return row["x"] + dx, f'{sh}<sub>{row["y"]}</sub>'
        if row["anchor"] == "bottom-right":
            return f'{sw}<sub>{row["x"] + 160 - dx}</sub>', f'{sh}<sub>{row["y"]}</sub>'
        raise ValueError(row["anchor"])

    out = ['<!-- CS2 in the Mojave HUD layer, injected into HUDMainMenu. Generated from sheets/hud.json. -->\n',
           '<rect name="CSNV_HUD">\n',
           '\t<user0>10</user0> <!-- crosshair arm length (set from CS2 cl_crosshairsize) -->\n',
           '\t<user1>5</user1> <!-- crosshair gap -->\n',
           '\t<user2>1</user2> <!-- crosshair thickness -->\n',
           '\t<user3>1</user3> <!-- centre dot: 2 = shown, 1 = hidden -->\n',
           '\t<visible>&true;</visible>\n']
    for hid in ("hud_health", "hud_caps", "hud_ammo"):
        x, y = pos(hud[hid])
        out.append(text_tile(hid, x, y, hud[hid]["format"].replace("{value}", "0").replace("{clip}", "0")
                             .replace("{reserve}", "0"), white))
    arm = hud["hud_armor"]
    x, y = pos(arm)
    out.append(image_tile("hud_armor_icon", x, f"{y}<add>2</add>", 28, 28, "armor.dds"))
    x, y = pos(arm, 36)
    out.append(text_tile("hud_armor", x, y, "0", white))
    # crosshair: four arms and a dot around the screen centre, sized by the user traits above
    cx, cy = f'{sw}<div>2</div>', f'{sh}<div>2</div>'
    L, G, T = ('<{op} src="parent()" trait="user0"/>', '<{op} src="parent()" trait="user1"/>',
               '<{op} src="parent()" trait="user2"/>')
    half_t = '<sub><copy src="parent()" trait="user2"/><div>2</div></sub>'
    arms = {
        "xh_left": (cx + G.format(op="sub") + L.format(op="sub"), cy + half_t, L.format(op="copy"), T.format(op="copy")),
        "xh_right": (cx + G.format(op="add"), cy + half_t, L.format(op="copy"), T.format(op="copy")),
        "xh_top": (cx + half_t, cy + G.format(op="sub") + L.format(op="sub"), T.format(op="copy"), L.format(op="copy")),
        "xh_bottom": (cx + half_t, cy + G.format(op="add"), T.format(op="copy"), L.format(op="copy")),
    }
    for name, (x, y, w, h) in arms.items():
        out.append(image_tile(name, x, y, w, h, "xhair.dds"))
    dot = image_tile("xh_dot", cx + half_t, cy + half_t, T.format(op="copy"), T.format(op="copy"), "xhair.dds")
    out.append(dot.replace("\t\t<visible>&true;</visible>\n", '\t\t<visible><copy src="parent()" trait="user3"/></visible>\n'))
    out.append("</rect>\n")
    return "".join(out)


def buy_xml(s):
    screen = s["buy_screen"]
    weapons = by_id(s["weapons"])
    rows_by_screen = {b["screen_row"]: b for b in s["buy_menu"]}
    out = ['<!-- CS2 in the Mojave buy screen layer, injected into MessageMenu. Generated from sheets/buy_screen.json. -->\n',
           '<rect name="CSNV_Buy">\n\t<visible>&true;</visible>\n']
    for row in screen:
        if row["kind"] in ("panel", "bar"):
            out.append(image_tile(row["id"], row["x"], row["y"], row["width"], row["height"], row["id"] + ".dds"))
            continue
        text = row["text"].replace("{caps}", "0")
        if row["id"] in rows_by_screen:
            b = rows_by_screen[row["id"]]
            text = text.replace("{name}", weapons[b["weapon"]]["name"]).replace("{price}", str(b["price_caps"]))
        font = 1 if row["id"] == "bs_header" else 3
        out.append(text_tile(row["id"], row["x"], row["y"], text, rgb(row["color"]), row["alpha"], font))
    out.append("</rect>\n")
    return "".join(out)


# ---------------------------------------------------------------- textures, ini, go

def solid(rgba, size=8):
    return [[tuple(rgba)] * size for _ in range(size)]


def xhair_default_rgba(cs2):
    presets = {0: (250, 50, 50), 1: (50, 250, 50), 2: (250, 250, 50), 3: (50, 50, 250), 4: (50, 250, 250)}
    preset = int(float(cs2["xhair_color"]["default"]))
    r, g, b = presets.get(preset, (int(cs2["xhair_r"]["default"]), int(cs2["xhair_g"]["default"]), int(cs2["xhair_b"]["default"])))
    return r, g, b, 255


def write_textures(s):
    tex = DATA / "textures" / "interface" / "csnv"
    tex.mkdir(parents=True, exist_ok=True)
    w, h, px = read_png(ROOT / "assets" / "armor.png")
    write_dds(tex / "armor.dds", w, h, px)
    for row in s["buy_screen"]:
        if row["kind"] in ("panel", "bar"):
            write_dds(tex / (row["id"] + ".dds"), 8, 8, solid(rgb(row["color"]) + [row["alpha"]]))
    write_dds(tex / "xhair.dds", 8, 8, solid(xhair_default_rgba(by_id(s["cs2_settings"]))))


def default_ini(s):
    cs2 = by_id(s["cs2_settings"])
    r, g, b, _ = xhair_default_rgba(cs2)
    return ("; CS2 in the Mojave: CS2 settings. Rewritten by csnv-launch.exe before every Play;\n"
            "; these are CS2's own defaults, used until the launcher has read your CS2 files.\n"
            "[Keys]\nBuyKey=48\n[Crosshair]\n"
            f"R={r}\nG={g}\nB={b}\nAlpha=255\n"
            f"Length={float(cs2['xhair_size']['default']) * 2:g}\nGap={4 + float(cs2['xhair_gap']['default']):g}\n"
            f"Thickness={max(1, round(float(cs2['xhair_thickness']['default']) * 2))}\nDot={int(float(cs2['xhair_dot']['default']))}\n"
            "Source=defaults\n")


def go_sheets(s):
    lines = ["// Code generated by tools/build.py from sheets/weapons.json and sheets/cs2_settings.json. DO NOT EDIT.", "",
             "package main", "", "var sheetWeapons = []weaponRow{"]
    for w in s["weapons"]:
        lines.append('\t{ID: "%s", Name: "%s", BaseForm: 0x%s, PluginForm: 0x%s, DamageMult: %g, ClipSize: %d, FireRateMult: %g, Automatic: %s},'
                     % (w["id"], w["name"], w["base_form"], w["plugin_form"], w["damage_mult"], w["clip_size"],
                        w["fire_rate_mult"], "true" if w["automatic"] else "false"))
    lines += ["}", "", "var sheetCS2Defaults = map[string]string{"]
    for r in s["cs2_settings"]:
        lines.append('\t"%s": "%s",' % (r["cs2_key"], r["default"]))
    lines += ["}", ""]
    return "\n".join(lines)


# ---------------------------------------------------------------- main

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--version", default="0.1.0")
    ap.add_argument("--no-exe", action="store_true", help="skip the Go build (scripts and XML only)")
    ap.add_argument("--release", action="store_true", help="fail instead of warning when vendor/jip_nvse.dll is missing")
    args = ap.parse_args()

    if subprocess.run([sys.executable, str(ROOT / "tools" / "preflight.py")], stdout=subprocess.DEVNULL).returncode:
        sys.exit("preflight is not clean: run tools/preflight.py and fix the sheets first")
    s = load_sheets()

    shutil.rmtree(STAGE, ignore_errors=True)
    udf = DATA / "NVSE" / "user_defined_functions" / "csnv"
    runner = DATA / "NVSE" / "Plugins" / "scripts"
    menus = DATA / "menus" / "csnv"
    config = DATA / "config"
    for d in (udf, runner, menus, config):
        d.mkdir(parents=True, exist_ok=True)
    for name, make in SCRIPTS.items():
        text = make(s)
        check_script_limits(name, text)
        (udf / f"{name}.txt").write_text(text, newline="\r\n")
    (runner / "ln_csnv.txt").write_text(RUNNER, newline="\r\n")
    (menus / "csnv_hud.xml").write_text(hud_xml(s), newline="\r\n")
    (menus / "csnv_buy.xml").write_text(buy_xml(s), newline="\r\n")
    (config / INI).write_text(default_ini(s), newline="\r\n")
    write_textures(s)
    (ROOT / "launcher" / "sheets_gen.go").write_text(go_sheets(s))
    subprocess.run(["gofmt", "-w", "sheets_gen.go"], cwd=ROOT / "launcher", check=True)

    managed = STAGE / "CSNV"
    managed.mkdir(parents=True, exist_ok=True)
    for name in ("README.md", "CREDITS.md", "TESTING.md", "LICENSE"):
        if (ROOT / name).exists():
            shutil.copy(ROOT / name, managed / name)
    if JIP_DLL.exists():
        plug = DATA / "NVSE" / "Plugins"
        shutil.copy(JIP_DLL, plug / "jip_nvse.dll")
        (plug / "textinput").mkdir(exist_ok=True)  # part of JIP LN's own install (its text-input menu)
        shutil.copy(ROOT / "vendor" / "textinput" / "texteditmenu.xml", plug / "textinput" / "texteditmenu.xml")
        shutil.copy(ROOT / "vendor" / "JIP-LN-NVSE-LICENSE.txt", managed / "JIP-LN-NVSE-LICENSE.txt")
    elif args.release:
        sys.exit("vendor/jip_nvse.dll is missing: a release without JIP LN NVSE does not work (see vendor/README.md)")
    else:
        print("WARNING: vendor/jip_nvse.dll is missing; the package will not work until it is added (see vendor/README.md)")

    if not args.no_exe:
        subprocess.run(["go", "build", "-trimpath", "-ldflags", "-s -w -H windowsgui", "-o", str(managed / "csnv-launch.exe"), "."],
                       cwd=ROOT / "launcher", check=True, env={**__import__("os").environ, "GOOS": "windows", "GOARCH": "amd64", "CGO_ENABLED": "0"})

    zpath = ROOT / "build" / f"CSNV-{args.version}.zip"
    with zipfile.ZipFile(zpath, "w", zipfile.ZIP_DEFLATED) as z:
        for f in sorted(STAGE.rglob("*")):
            if f.is_file():
                z.write(f, f.relative_to(STAGE).as_posix())
    print(f"built {zpath.relative_to(ROOT)} ({zpath.stat().st_size} bytes)")
    for f in sorted(STAGE.rglob("*")):
        if f.is_file():
            print("  ", f.relative_to(STAGE).as_posix())


if __name__ == "__main__":
    main()
